id: PD25C5B27
initial_creation_type: ocr
source_metadata:
  volumes:
    4af84bd17d1b4f4c9ba7bd1e86982e63:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྙིང་པོའི་རྣམ་པར་བཤད་པ།
      total_pages: 1682
      volume_number: 56
